//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTRENT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ID { get; set; }
        public string ClientName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Adress1 { get; set; }
        public string Adress2 { get; set; }
        public string LicenseNumber { get; set; }
        public System.DateTime LicenceExpiration { get; set; }
        public int NacionalityId { get; set; }
        public string IdentificationNumber { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
    }
}
