//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTRENT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public string Rid { get; set; }
        public int Id { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public string Descripcion { get; set; }
        public int FieldOrder { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime CreatedDateBy { get; set; }
        public Nullable<System.DateTime> ModiFiedDateBy { get; set; }
    }
}
