//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTRENT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Adress1 { get; set; }
        public string Adress2 { get; set; }
        public string PhoneNumber { get; set; }
        public string ContactName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
    }
}
