//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTRENT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiclesMaintenaceInfo
    {
        public int Id { get; set; }
        public int VehicleID { get; set; }
        public int LastMileageService { get; set; }
        public int IntervalMileageService { get; set; }
        public System.DateTime LastServiceDate { get; set; }
        public System.DateTime NextServiceDate { get; set; }
        public System.DateTime NextInspectionDate { get; set; }
        public System.DateTime PlateExpirationDate { get; set; }
        public int InsuranceCode { get; set; }
        public string InsurancePolicyNumber { get; set; }
        public System.DateTime InsuranceExpirationDate { get; set; }
        public decimal InsuranceAmount { get; set; }
    }
}
