//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTRENT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int VehicleId { get; set; }
        public string PlateNumber { get; set; }
        public string Chassis { get; set; }
        public int Class { get; set; }
        public string Description { get; set; }
        public int Brand { get; set; }
        public int Model { get; set; }
        public string Color { get; set; }
        public int Transmission { get; set; }
        public int Fuel { get; set; }
        public string ManufactureYear { get; set; }
        public int Status { get; set; }
        public System.DateTime AcquisitionDate { get; set; }
        public int Owner { get; set; }
        public string Mileage { get; set; }
        public decimal Price1 { get; set; }
        public decimal Price2 { get; set; }
        public decimal Price3 { get; set; }
        public decimal Price4 { get; set; }
        public decimal Price5 { get; set; }
        public decimal Price1A { get; set; }
        public decimal Price2A { get; set; }
        public decimal Price3A { get; set; }
        public decimal Price4A { get; set; }
        public decimal Price5A { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
