//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTRENT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiclesPrice
    {
        public int PriceId { get; set; }
        public int VehicleId { get; set; }
        public int DayRange1 { get; set; }
        public int DayRange2 { get; set; }
        public decimal Price1 { get; set; }
        public decimal Price2 { get; set; }
    }
}
