//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTRENT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiclesExpenss
    {
        public int Id { get; set; }
        public int VehicleId { get; set; }
        public int ExpenseType { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public decimal ExpenseAmount { get; set; }
        public string ExpenseNotes { get; set; }
    }
}
