//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTRENT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFilesDescription
    {
        public string NombreTabla { get; set; }
        public string NombreCampo { get; set; }
        public string TipoDatos { get; set; }
        public Nullable<short> Precision { get; set; }
        public Nullable<int> Escala { get; set; }
        public string PermiteNulos { get; set; }
        public string ValorDefecto { get; set; }
        public string PrimaryKey { get; set; }
        public string NombreIndice { get; set; }
    }
}
