//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTRENT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwVehicle
    {
        public int VehicleId { get; set; }
        public string PlateNumber { get; set; }
        public string Chassis { get; set; }
        public int ClassCode { get; set; }
        public string clasDescription { get; set; }
        public string Description { get; set; }
        public int brandCode { get; set; }
        public string brandDescription { get; set; }
        public int modelCode { get; set; }
        public string modelDescription { get; set; }
        public string Color { get; set; }
        public int tranCode { get; set; }
        public string tranDescription { get; set; }
        public string ManufactureYear { get; set; }
        public int statCode { get; set; }
        public string statDescription { get; set; }
        public System.DateTime AcquisitionDate { get; set; }
        public int ownerCode { get; set; }
        public string OwnName { get; set; }
        public string Mileage { get; set; }
        public decimal Price1 { get; set; }
        public decimal Price2 { get; set; }
        public decimal Price3 { get; set; }
        public decimal Price4 { get; set; }
        public decimal Price5 { get; set; }
        public decimal Price1A { get; set; }
        public decimal Price2A { get; set; }
        public decimal Price3A { get; set; }
        public decimal Price4A { get; set; }
        public decimal Price5A { get; set; }
        public byte[] binPicture { get; set; }
        public int fuelCode { get; set; }
        public string fuelDescription { get; set; }
    }
}
